### ISSUE TITLE
Custom RenderMan shader (*.so and *.oso)

### ISSUE THREAD

**Issue by nyue** [ababak/maya2katana#2]
We have custom shaders which we contracted out to be developed.

We can load them both in Maya and Katana

What is the correct way to let maya2katana know about those custom shaders so that the conversion script translate those information across from Maya to Katana ?

Cheers

**Comment by ababak** [comment]
Basically, you need to create an XML file in `renderer/prman/nodes` by copy/pasting a fresh node from Katana (you'll need to strip two levels of XML structure and remove x and y attributes of the top node -- see other nodes to get a clue). If all node parameters match in Maya and Katana, you'll just need to edit `renderer/prman/__init__.py` and add the node to `premap` and `mappings` dictionaries (see other nodes).
